server:
  port: 8083
  servlet:
    context-path: /api
spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 6  #Redis索引0~15，默认为0
    host: 39.101.195.100
    port: 6379
    password: zs@123..
    lettuce: # 这里标明使用lettuce配置
      pool:
        max-active: 8   #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms  #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 5     #连接池中的最大空闲连接
        min-idle: 0     #连接池中的最小空闲连接
    timeout: 10000ms    #连接超时时间（毫秒）

# mybatis-plus
mybatis-plus:
  type-aliases-package: com.zs.modules.*.entity
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: assign_id
    # 控制台是否开启mybatis-plus logo
    banner: false
  configuration:
    # 驼峰
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
# 日志配置
logging:
  level:
    org.apache.ibatis: DEBUG

security:
  white:
    url:
      - /login
      - /hello
      - /list