spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zs_admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: zsAdmin
    password: zsAdmin
    druid:
      initial-size: 5 # 初始化连接数
      min-idle: 5 # 最小空闲连接数
      max-active: 20 # 最大连接数
      test-on-borrow: true # 测试连接是否可用
      validation-query: SELECT 1
      use-global-data-source-stat: true # 合并多个DruidDataSource的监控数据
      web-stat-filter:
        enabled: true # 是否开启web监控
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 排除监控的URL路径
      stat-view-servlet:
        enabled: true # 是否开启监控页面
        url-pattern: /druid/* # 监控页面的访问路径
        #        login-username: admin
        #        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: Zs@123..
      database: 0
      # 毫秒
      timeout: 10000
      lettuce:
        pool:
          max-active: 10
          max-wait: -1
          max-idle: 5
          min-idle: 0